[2022-07-21 09:22:00,477] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: StackExchange.check_sql_conn manual__2022-07-21T09:21:45.423642+00:00 [queued]>
[2022-07-21 09:22:00,502] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: StackExchange.check_sql_conn manual__2022-07-21T09:21:45.423642+00:00 [queued]>
[2022-07-21 09:22:00,508] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-07-21 09:22:00,518] {taskinstance.py:1239} INFO - Starting attempt 1 of 6
[2022-07-21 09:22:00,522] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-07-21 09:22:00,573] {taskinstance.py:1259} INFO - Executing <Task(BranchPythonOperator): check_sql_conn> on 2022-07-21 09:21:45.423642+00:00
[2022-07-21 09:22:00,581] {standard_task_runner.py:52} INFO - Started process 255 to run task
[2022-07-21 09:22:00,634] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'StackExchange', 'check_sql_conn', 'manual__2022-07-21T09:21:45.423642+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/stackexchange_dag.py', '--cfg-path', '/tmp/tmptjr7z4gu', '--error-file', '/tmp/tmpd2862nq2']
[2022-07-21 09:22:00,636] {standard_task_runner.py:77} INFO - Job 12: Subtask check_sql_conn
[2022-07-21 09:22:00,885] {logging_mixin.py:109} INFO - Running <TaskInstance: StackExchange.check_sql_conn manual__2022-07-21T09:21:45.423642+00:00 [running]> on host 98e81b5638d8
[2022-07-21 09:22:01,036] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=saad
AIRFLOW_CTX_DAG_ID=StackExchange
AIRFLOW_CTX_TASK_ID=check_sql_conn
AIRFLOW_CTX_EXECUTION_DATE=2022-07-21T09:21:45.423642+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-21T09:21:45.423642+00:00
[2022-07-21 09:22:01,038] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 203, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/stackexchange_dag.py", line 28, in _check_sql_conn
    raise TypeError("Only integers are allowed")
TypeError: Only integers are allowed
[2022-07-21 09:22:01,119] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=StackExchange, task_id=check_sql_conn, execution_date=20220721T092145, start_date=20220721T092200, end_date=20220721T092201
[2022-07-21 09:22:01,145] {standard_task_runner.py:92} ERROR - Failed to execute job 12 for task check_sql_conn
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 203, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/stackexchange_dag.py", line 28, in _check_sql_conn
    raise TypeError("Only integers are allowed")
TypeError: Only integers are allowed
[2022-07-21 09:22:01,199] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-07-21 09:22:01,355] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
